/* eslint-disable no-dupe-keys */
/*
 * @Autor: Riman
 * @Date: 2022-06-30 10:01:28
 * @LastEditors: zq636443 zq636443@163.com
 * @LastEditTime: 2024-12-11 17:14:17
 * @Description:
 */
// 公共样式
export const commonStyle = {
  rotate: 0,
  opacity: 1,
};

export const commonAttr = {
  animations: [],
  events: [{ params: {} }],
  // groupStyle: {}, // 当一个组件成为 Group 的子组件时使用
  isLock: false, // 是否锁定组件
  isView: true,
};

// 抽奖组件的类型
export const drawTypeList = [
  "GRID_WHEEL",
  "BIG_WHEEL",
  "SCRATCH_CARD",
  "RED_RAIN",
  "SLOT_MACHINE",
  "MYSTERY_BOX",
  "SMASH_EGG",
  "AWARD",
  "MONOPOLY",
  "CARD",
  "ANSWER",
  "COMPOSITE_GAME",
  "RECEIVE_GOLD",
  "K_LINE_GAME",
  "PUZZLE_GAME",
  "DOLL_MACHINE",
  "FLIP"
];

// 编辑器左侧组件列表
const list = [
  // {
  //   id: '0',
  //   component: 'TEXT',
  //   category: 'base',
  //   type: 'TEXT',
  //   label: '文字组件',
  //   propValue: { text: '文字内容', groupStyle: {} },
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/text.jpg',
  //   fontName: '默认字体',
  //   fontFamily: '',
  //   fontBorderWidth: 1,
  //   textStroke: false,
  //   style: {
  //     width: 100,
  //     height: 36,
  //     previewWidth: 160,
  //     fontSize: 14,
  //     fontWeight: 500,
  //     lineHeight: '',
  //     letterSpacing: 0,
  //     textColor: 'rgba(0,0,0,1)',
  //     fontFamily: '',
  //     WebkitTextStrokeColor: '#979797',
  //     WebkitTextStrokeWidth: 0,
  //     verticalAlign: 'middle',
  //     textAlign: 'center',
  //     openTextShadow: false
  //   },
  // },
  {
    id: '1',
    component: 'RICH_TEXT',
    category: 'base',
    type: 'RICH_TEXT',
    label: '富文本组件',
    propValue: { text: '<p>富文本内容</p>', groupStyle: {} },
    icon: 'https://media.jiniutech.com/yunying/1_elements/text.png',
    style: {
      width: 80,
      height: 21,
      previewWidth: 160,
      fontSize: 14,
      fontWeight: 500,
      lineHeight: '',
      letterSpacing: 0,
      textAlign: '',
      textColor: 'rgba(0,0,0,1)',
      textAlign: 'center'
    },
  },
  {
    id: '2',
    component: 'IMAGE',
    category: 'base',
    type: 'IMAGE',
    label: '图片组件',
    propValue: { image: 'https://media.jiniutech.com/yunying/2_default/MRT.png', groupStyle: {} },
    icon: 'https://media.jiniutech.com/yunying/1_elements/image.png',
    style: {
      width: 375,
      height: 200,
      previewWidth: 750,
    },
    imageShowStyle: 'WIDTH_MATCH'
  },
  // {
  //   id: '3',
  //   component: 'GRID_WHEEL',
  //   category: 'REWARD_ELEMENT',
  //   type: 'GRID_WHEEL',
  //   label: '九宫格组件',
  //   propValue: {
  //     image: 'https://media.jiniutech.com/yunying/1_elements/grid_wheel.png',
  //     groupStyle: {},
  //   },
  //   colors: {
  //     prizeTextColor: 'rgba(102, 102, 102, 1)',
  //     textColor: 'rgba(83,83,83,1)',
  //   },
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/grid_wheel.png',
  //   style: {
  //     width: 330,
  //     height: 370,
  //     textColor: 'rgba(84,84,84,1)',
  //     previewWidth: 660,
  //   },
  //   drawConsumeType: 'LEFT_COUNT',
  //   showRemainingValue: true,
  //   hasNoChangeTip: '活动次数已达上限，下次再来吧',
  //   hasChangeTip: '快去完成任务，获得抽奖机会吧',
  //   showAttendUser: true,
  //   // showLeftCount: true,
  //   drawImage: 'https://media.jiniutech.com/yunying/2_default/JGG_CJT.gif',
  //   prizes: [
  //     {
  //       image: 'https://media.jiniutech.com/yunying/2_default/XXCY.png',
  //       itemName: '谢谢参与',
  //       itemPosition: '1,3,5,7',
  //       prizeVirtualId: 'eiu94fccngg00000',
  //       probability: 50,
  //     },
  //     {
  //       image: 'https://media.jiniutech.com/yunying/2_default/HBY_HBT.png',
  //       itemName: '现金红包',
  //       itemPosition: '2,4,6,8',
  //       probability: 50,
  //       prizeVirtualId: 'uqjvmvlg4z400000',
  //     },
  //   ],
  // },
  {
    id: '4',
    component: 'TASK',
    category: 'TASK_ELEMENT',
    type: 'TASK',
    label: '任务卡片',
    colors: {
      titleColor: 'rgba(84,84,84,1)',
      textColor: 'rgba(134, 140, 148,1)'
    },
    propValue: {
      image: 'https://media.jiniutech.com/yunying/1_elements/grid_wheel.png',
      groupStyle: {},
    },
    icon: 'https://media.jiniutech.com/yunying/1_elements/task.png',
    style: {
      width: 330,
      height: 40,
      textColor: 'rgba(84,84,84,1)',
      previewWidth: 660,
    },
    isShowing: true,
    image: 'https://media.jiniutech.com/yunying/2_default/RW_ICON.png',
    goButton: 'https://media.jiniutech.com/yunying/2_default/RW_QWC.png',
    finishButton: 'https://media.jiniutech.com/yunying/2_default/RW_YWC.png',
    taskLimitShow: true,
    task: {
      name: '这里是任务标题',
      description: '这里是任务描述',
      rewardValue: 1,
      attendLimit: 1,
      eachCount: '',
      subTasks: [],
      startTime: '',
      endTime: '',
      finishCount: '',
      taskType: 'EVENT',
      browseTime: 5,
      tip: '',
      isFinishJump: true,
      attendType: 'DURING',
      duration: false,
      backrewardCount: 0,
      descShowType: 'QUESTION_MARK',
      rewardType: 'LEFT_COUNT',
      clickEvent: {
        clickType: 'NONE',
      },
      taskEventType: '',
      taskEventId: '',
      taskEventName: '',
      parameter:undefined,
      parameter2:undefined
    },
  },
  {
    id: '5',
    component: 'BIG_WHEEL',
    category: 'REWARD_ELEMENT',
    type: 'BIG_WHEEL',
    label: '大转盘组件',
    colors: {
      pannelColor1: 'rgba(255, 245, 211, 1)',
      pannelColor2: 'rgba(255, 255, 253, 1)',
      pennelDivideColor: 'rgba(255, 146, 102, 1)',
      prizeTextColor: 'rgba(255, 97, 58, 1)',
      textColor: 'rgba(83,83,83,1)',
    },
    propValue: {
      image: 'https://media.jiniutech.com/yunying/1_elements/big_wheel.png',
      groupStyle: {},
    },
    icon: 'https://media.jiniutech.com/yunying/1_elements/big_wheel.png',
    style: {
      width: 330,
      height: 360,
      textColor: 'rgba(83,83,83,1)',
      previewWidth: 660
    },
    drawConsumeType: 'LEFT_COUNT',
    showRemainingValue: true,
    hasNoChangeTip: '活动次数已达上限，下次再来吧',
    hasChangeTip: '快去完成任务，获得抽奖机会吧',
    showAttendUser: true,
    // showLeftCount: true,
    drawButton: 'https://media.jiniutech.com/yunying/2_default/DZP_ANT.png',
    borderImg: 'https://media.jiniutech.com/yunying/2_default/DZP_WKT.png',
    prizes: [
      {
        image: 'https://media.jiniutech.com/yunying/2_default/XXCY.png',
        itemName: '谢谢参与',
        itemPosition: '1,3,5',
        prizeVirtualId: 'eiu94fccngg00000',
        probability: 50,
      },
      {
        image: 'https://media.jiniutech.com/yunying/2_default/HBY_HBT.png',
        itemName: '现金红包',
        itemPosition: '2,4,6',
        probability: 50,
        prizeVirtualId: 'uqjvmvlg4z400000',
      },
    ],
  },
  // {
  //   id: '6',
  //   component: 'SCRATCH_CARD',
  //   category: 'REWARD_ELEMENT',
  //   type: 'SCRATCH_CARD',
  //   label: '刮刮卡组件',
  //   propValue: {
  //     image: 'https://media.jiniutech.com/yunying/1_elements/scratch_card.png',
  //     groupStyle: {},
  //   },
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/scratch_card.png',
  //   style: {
  //     width: 330,
  //     height: 230,
  //     textColor: 'rgba(83,83,83,1)',
  //     previewWidth: 660
  //   },
  //   drawConsumeType: 'LEFT_COUNT',
  //   showRemainingValue: true,
  //   hasNoChangeTip: '活动次数已达上限，下次再来吧',
  //   hasChangeTip: '快去完成任务，获得抽奖机会吧',
  //   showAttendUser: true,
  //   // showLeftCount: true,
  //   beforeScratch: 'https://media.jiniutech.com/yunying/2_default/GGK_GQ.png',
  //   afterScratch: 'https://media.jiniutech.com/yunying/2_default/GGK_GH.png',
  //   prizes: [],
  // },
  {
    id: '7',
    component: 'BANNER',
    category: 'base',
    type: 'BANNER',
    label: '轮播组件',
    propValue: {
      image: 'https://media.jiniutech.com/yunying/1_elements/banner.png',
      groupStyle: {},
    },
    icon: 'https://media.jiniutech.com/yunying/1_elements/banner.png',
    style: {
      width: 300,
      height: 150,
      previewWidth: 600
    },
    autoplay: true,
    defaultColor: '#666',
    activeColor: '#EDBB62',
    delay: 1, // 滚动速率&切换速率（1倍）
    spaceBetween: 10,
    pagination: 'BULLETS',
    loop: true,
    effect: 'SLIDE',
    direction: 'HORIZONTAL',
    bannerType: 'SINGLE',
    images: [
      {
        clickEvent: { clickType: 'NONE' },
        isShowing: true,
        name: "默认1",
        type: "IMAGE",
        url: "https://media.jiniutech.com/yunying/2_default/MRT.png",
        imgVirtualId: "1"
      },
      {
        clickEvent: { clickType: 'NONE' },
        isShowing: true,
        name: "默认2",
        type: "IMAGE",
        url: "https://media.jiniutech.com/yunying/2_default/MRT.png",
        imgVirtualId: "2"
      },
      {
        clickEvent: { clickType: 'NONE' },
        isShowing: true,
        name: "默认3",
        type: "IMAGE",
        url: "https://media.jiniutech.com/yunying/2_default/MRT.png",
        imgVirtualId: "3"
      },
    ],
    hasNoChangeTip: '活动次数已达上限，下次再来吧',
    hasChangeTip: '快去完成任务，获得抽奖机会吧',
    showAttendUser: true,
    showLeftCount: true,
  },
  {
    id: '8',
    component: 'MARQUEE',
    category: 'base',
    type: 'MARQUEE',
    label: '跑马灯组件',
    propValue: {
      image: 'https://media.jiniutech.com/yunying/1_elements/marquee.png',
      groupStyle: {},
    },
    icon: 'https://media.jiniutech.com/yunying/1_elements/marquee.png',
    style: {
      width: 220,
      height: 30,
      textColor: 'rgba(78,78,78,1)',
      previewWidth: 440
    },
    isShowing: true,
    isSuspend: false,
    records: [
      "用户178****666获得8.88元红包",
      "用户088****535获得0.88元红包",
    ],
    showCount: 10,
    fontSize: 14,
    speed: 1,
    clickEvent: {
      clickType: "NONE",
    },
    direction: "VERTICAL",
    // direction: "HORIZONTAL",
    dataType: "NONE",
    productType:'SMART_INVESTMENT'
  },
  // {
  //   id: '9',
  //   component: 'COUNTDOWN',
  //   category: 'base',
  //   type: 'COUNTDOWN',
  //   label: '倒计时组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/countdown.png',
  //   style: {
  //     width: 310,
  //     height: 110,
  //     previewWidth: 620,
  //   },
  //   propValue: {
  //     image: 'https://media.jiniutech.com/yunying/1_elements/countdown.png',
  //     groupStyle: {},
  //   },
  //   endTime: '',
  //   isShowDays: true,
  //   effectType: 'NORMAL',
  //   timeFrameBackgroundImage: '',
  //   endEffectType: 'NORMAL',
  //   timeUnitColor: 'rgba(78,78,78,1)',
  //   timeNumColor: 'rgba(0,0,0,1)'
  // },
  // {
  //   id: '10',
  //   component: 'PK_TOPIC',
  //   category: 'base',
  //   type: 'PK_TOPIC',
  //   label: '话题PK组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/pk_topic.png',
  //   style: {
  //     width: 340,
  //     height: 160,
  //     textColor: 'rgba(84,84,84,1)',
  //     previewWidth: 680
  //   },
  //   propValue: {
  //     image: 'https://media.jiniutech.com/yunying/1_elements/pk_topic.png',
  //     groupStyle: {},
  //   },
  //   topic: '周末怎么过？',
  //   negative: '宅',
  //   positive: '出门',
  //   backgroundColor: '',
  //   virtualNegative: 5,
  //   virtualPositive: 5,
  // },
  {
    id: '11',
    component: 'TAB',
    category: 'base',
    type: 'TAB',
    label: 'Tab组件',
    icon: 'https://media.jiniutech.com/yunying/1_elements/tab_container.png',
    style: {
      width: 375,
      height: 450,
      textColor: 'rgba(83,83,83,1)',
      previewWidth: 750
    },
    propValue: {
      image: 'https://media.jiniutech.com/yunying/1_elements/tab.png',
      groupStyle: {},
    },
    position: 'TOP',
    showTitle: false,
    activeColor: "rgba(191,131,46,1)",
    unActiveColor: '',
    fontSize: 16,
    mode:'TAB',
    tabItems: [
      {
        title: "标题1",
        type: 'CURRENT',
        selectedIcon: 'https://media.jiniutech.com/production/image/a41547e6-f191-4cec-8f46-71537f15a9be.png',
        unSelectedIcon: 'https://media.jiniutech.com/yunying/2_default/TAB_OFF.png'
      },
      {
        title: "标题2",
        type: 'CURRENT',
        selectedIcon: 'https://media.jiniutech.com/production/image/4e1434d1-d4a5-4b4d-89c6-e714ca83093e.png',
        unSelectedIcon: 'https://media.jiniutech.com/yunying/2_default/TAB_OFF.png'
      },
      {
        title: "标题3",
        type: 'CURRENT',
        selectedIcon: 'https://media.jiniutech.com/production/image/2db0f99a-aab2-47d3-bb2b-ba2b6b5ca557.png',
        unSelectedIcon: 'https://media.jiniutech.com/yunying/2_default/TAB_OFF.png'
      },
    ],
  },
  // {
  //   id: '12',
  //   component: 'RED_RAIN',
  //   category: 'REWARD_ELEMENT',
  //   type: 'RED_RAIN',
  //   label: '红包雨组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/red_rain.png',
  //   hasNoChangeTip: '活动次数已达上限，下次再来吧',
  //   hasChangeTip: '快去完成任务，获得抽奖机会吧',
  //   style: {
  //     width: 280,
  //     height: 100,
  //     textColor: 'rgba(83,83,83,1)',
  //     previewWidth: 680
  //   },
  //   propValue: {
  //     image: 'https://media.jiniutech.com/yunying/1_elements/red_rain.png',
  //     groupStyle: {},
  //   },
  //   drawConsumeType: 'LEFT_COUNT',
  //   showRemainingValue: true,
  //   // showLeftCount: true,
  //   isShowing: true,
  //   atLeast: 10,
  //   gameTime: 10,
  //   clickRed: "https://media.jiniutech.com/yunying/2_default/HBY_DJT.png",
  //   drawButton: "https://media.jiniutech.com/yunying/2_default/HBY_KST.png",
  //   redPacket: "https://media.jiniutech.com/yunying/2_default/HBY_HBT.png",
  //   prizes: [],
  //   prizePools: {},

  // },
  // {
  //   id: '13',
  //   component: 'DATA',
  //   category: 'base',
  //   type: 'DATA',
  //   label: '数据组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/data.png',
  //   style: {
  //     width: 90,
  //     height: 20,
  //     textColor: 'rgba(84,84,84,1)',
  //     previewWidth: 180,
  //     fontSize: 12,
  //   },
  //   dataType: 'CRR_REMAINING_LEFT_COUNT',
  //   propValue: {
  //     image: 'https://media.jiniutech.com/yunying/1_elements/data.png',
  //     groupStyle: {}
  //   },
  // },
  {
    id: '14',
    component: 'VIDEO',
    category: 'base',
    type: 'VIDEO',
    label: '视频组件',
    icon: 'https://media.jiniutech.com/yunying/1_elements/video.png',
    style: {
      width: 375,
      height: 280,
      previewWidth: 750
    },
    enable: false,
    isShowLike: false,
    isShowView: false,
    url: ''
  },
  {
    id: '15',
    component: 'AUDIO',
    category: 'base',
    type: 'AUDIO',
    label: '音频组件',
    icon: 'https://media.jiniutech.com/yunying/1_elements/audio.png',
    style: {
      width: 300,
      height: 54,
      textColor: 'rgba(83,83,83,1)',
      previewWidth: 600
    },
    model: 'CAR_STYLE',
    showType: 'BAR_STYLE',
    loop: true,
  },
  // {
  //   id: '16',
  //   component: 'SLOT_MACHINE',
  //   category: 'REWARD_ELEMENT',
  //   type: 'SLOT_MACHINE',
  //   label: '老虎机组件',
  //   icon: '	https://media.jiniutech.com/yunying/1_elements/slot_machine.png',
  //   style: {
  //     width: 300,
  //     height: 280,
  //     textColor: 'rgba(84,84,84,1)',
  //     previewWidth: 600
  //   },
  //   drawConsumeType: 'LEFT_COUNT',
  //   showRemainingValue: true,
  //   prizes: [],
  //   drawImage: 'https://media.jiniutech.com/yunying/2_default/LHJ_AN.png',
  //   frameImage: 'https://media.jiniutech.com/yunying/2_default/LHJ_BG.png',
  //   isShowing: true,
  //   hasNoChangeTip: '活动次数已达上限，下次再来吧',
  //   hasChangeTip: '快去完成任务，获得抽奖机会吧',
  //   // showLeftCount: true,
  // },
  {
    id: '17',
    component: 'MYSTERY_BOX',
    category: 'REWARD_ELEMENT',
    type: 'MYSTERY_BOX',
    label: '盲盒组件',
    icon: 'https://media.jiniutech.com/yunying/1_elements/mystery_box.png',
    style: {
      width: 250,
      height: 250,
      textColor: 'rgba(83,83,83,1)',
      previewWidth: 500
    },
    drawConsumeType: 'LEFT_COUNT',
    showRemainingValue: true,
    prizes: [],
    boxAfter: "https://media.jiniutech.com/yunying/2_default/MH_KQH.gif",
    boxBefore: "https://media.jiniutech.com/yunying/2_default/MH_KQQ.gif",
    buttonAfter: "https://media.jiniutech.com/yunying/2_default/MH_KQ2.png",
    buttonBefore: "https://media.jiniutech.com/yunying/2_default/MH_KQ1.png",
    buttonHeight: 40,
    // buttonWidth: 200,
    // showLeftCount: true,
    showLeftCountType: 'TEXT',
    hasNoChangeTip: '活动次数已达上限，下次再来吧',
    hasChangeTip: '快去完成任务，获得抽奖机会吧',
  },
  // {
  //   id: '18',
  //   component: 'MYSTERY_BOX_2',
  //   category: 'REWARD_ELEMENT',
  //   type: 'MYSTERY_BOX_2',
  //   label: '盲盒组件2',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/mystery_box.png',
  //   style: {
  //     width: 300,
  //     height: 300,
  //   },
  //   prizes:[],
  //   boxAfter: "https://media.jiniutech.com/yunying/2_default/MH_KQH.gif",
  //   boxBefore: "https://media.jiniutech.com/yunying/2_default/MH_KQQ.gif",
  //   boxNumber: 6,
  //   showLeftCount: true,
  //   hasNoChangeTip: '活动次数已达上限，下次再来吧',
  //   hasChangeTip: '快去完成任务，获得抽奖机会吧',
  // },
  {
    id: '19',
    component: 'SMASH_EGG',
    category: 'REWARD_ELEMENT',
    type: 'SMASH_EGG',
    label: '砸金蛋组件',
    icon: 'https://media.jiniutech.com/yunying/1_elements/smash_egg.png',
    style: {
      width: 300,
      height: 200,
      previewWidth: 600
    },
    colors: {
      textColor: 'rgba(84,84,84,1)',
    },
    hasNoChangeTip: '活动次数已达上限，下次再来吧',
    hasChangeTip: '快去完成任务，获得抽奖机会吧',
    drawConsumeType: 'LEFT_COUNT',
    showRemainingValue: true,
    prizes: [],
    bottomImage: 'https://media.jiniutech.com/yunying/2_default/egg/dipan.png',
    eggsImages: [
      'https://media.jiniutech.com/yunying/2_default/egg/dan.png',
      'https://media.jiniutech.com/yunying/2_default/egg/dan.png',
      'https://media.jiniutech.com/yunying/2_default/egg/dan.png',
    ],
    hammerImages: 'https://media.jiniutech.com/yunying/2_default/egg/chuizi.gif',
    hitImages: [
      'https://media.jiniutech.com/yunying/2_default/egg/baozha.gif',
      'https://media.jiniutech.com/yunying/2_default/egg/baozha.gif',
      'https://media.jiniutech.com/yunying/2_default/egg/baozha.gif'
    ],
    // showLeftCount: true,
    showType: 'cross'
  },
  // {
  //   id: '20',
  //   component: 'LUCK_DOG',
  //   category: 'REWARD_ELEMENT',
  //   type: 'LUCK_DOG',
  //   label: '锦鲤组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/luck_dog.png',
  //   style: {
  //     width: 330,
  //     height: 120,
  //     textColor: 'rgba(191,131,46,1)',
  //     previewWidth: 660,
  //   },
  //   luckDog: {
  //     score: 999,
  //     openTime: ''
  //   },
  //   price: 999,
  //   prizes: [],
  //   attendButton: 'https://media.jiniutech.com/yunying/2_default/KJ_LJCY.png',
  // },
  // {
  //   id: '21',
  //   component: 'AWARD',
  //   category: 'REWARD_ELEMENT',
  //   type: 'AWARD',
  //   label: '领奖组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/award.png',
  //   style: {
  //     width: 250,
  //     height: 86,
  //     textColor: "rgba(84,84,84,1)",
  //     previewWidth: 500
  //   },
  //   drawConsumeType: 'LEFT_COUNT',
  //   showRemainingValue: true,
  //   isShowing: true,
  //   showCount: true,
  //   dateType: 'GLOBAL',
  //   countSize: 12,
  //   virtualCount: 0,
  //   awardButton: 'https://media.jiniutech.com/yunying/2_default/LJ_LJLQ.png',
  //   finishButton: 'https://media.jiniutech.com/yunying/2_default/LJ_YLQ.png',
  //   oneMoreButton: 'https://media.jiniutech.com/yunying/2_default/LJ_JXLQ.png',
  //   buttonHeight: '65',
  //   buttonWidth: '250',
  //   prizeName: '奖品包名称',
  //   prizeImage: 'https://media.jiniutech.com/yunying/2_default/HBY_HBT.png',
  //   prizes: [],
  // },
  // {
  //   id: '22',
  //   component: 'MONOPOLY',
  //   category: 'interaction',
  //   type: 'MONOPOLY',
  //   label: '大富翁组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/Monopoly.jpg',
  //   style: {
  //     width: 375,
  //     height: 530,
  //     previewWidth: 750,
  //     textColor: 'rgba(255,255,255,100)',
  //   },
  //   hasNoChangeTip: "今日游戏次数已达上限，下次再来吧",
  //   hasChangeTip: "快去完成任务，获得游戏机会吧",
  //   drawConsumeType: 'LEFT_COUNT',
  //   showRemainingValue: true,
  //   backgroundImage: 'https://media.jiniutech.com/yunying/2_default/monopoly/2_bg_circular.png',
  //   // startPoint: '', // 起点图标
  //   // endPoint: '', // 终点图标
  //   // imageElements: [], // 广告位配置
  //   goAlongType: 'RANDOM_DICE',
  //   doll: 'https://media.jiniutech.com/yunying/2_default/monopoly/doll.png', // 小人图标
  //   maxStep: 6, // 可投掷最大点数
  //   initStep: null, // 第一次投掷的点数
  //   hasLoopPrize: false, // 经过起点/终点时是否进行抽奖
  //   isLoop: true,
  //   isShowing: true,
  //   luckyGrids: [],
  //   prizeList: [], // 终点奖品
  //   prizes: [], // 格子通用奖池
  //   resetType: 'NEVER',
  //   single: false, // 是否开启格子抽奖
  //   images: [
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_start.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_special.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_special.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_special.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_special.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_special.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_normal.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_floor_special.png',
  //   ],
  //   diceImages: [
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_dice_1.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_dice_2.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_dice_3.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_dice_4.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_dice_5.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_dice_6.png',
  //     'https://media.jiniutech.com/yunying/2_default/monopoly/2_dice_vfx.gif',
  //   ],
  // },
  // {
  //   id: '23',
  //   component: 'CARD',
  //   category: 'prize',
  //   type: 'CARD',
  //   label: '集卡组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/card.png',
  //   style: {
  //     width: 375,
  //     height: 260,
  //     textColor: 'rgba(84,84,84,1)',
  //     previewWidth: 750,
  //   },
  //   buttonHeight: 60,
  //   buttonWidth: 250,
  //   drawType: 'TIMING',
  //   cardButton: 'https://media.jiniutech.com/yunying/2_default/JK_CK.png',
  //   cardImage: 'https://media.jiniutech.com/yunying/2_default/JK_KB.png',
  //   cardList: [
  //     {
  //       "frontImage": "https://media.jiniutech.com/yunying/2_default/JK_KM1.png",
  //       "name": "集",
  //     },
  //     {
  //       "frontImage": "https://media.jiniutech.com/yunying/2_default/JK_KM2.png",
  //       "name": "卡",
  //     },
  //     {
  //       "frontImage": "https://media.jiniutech.com/yunying/2_default/JK_KM3.png",
  //       "name": "赢",
  //     },
  //     {
  //       "frontImage": "https://media.jiniutech.com/yunying/2_default/JK_KM4.png",
  //       "name": "好",
  //     },
  //     {
  //       "frontImage": "https://media.jiniutech.com/yunying/2_default/JK_KM5.png",
  //       "name": "礼",
  //     },
  //   ],
  //   cardType: 'FIVE',
  //   continueButton: 'https://media.jiniutech.com/yunying/2_default/JK_JXCK.png',
  //   drawButton: 'https://media.jiniutech.com/yunying/2_default/JK_CJ.png',
  //   openTip: '集齐5张卡片即可抽大奖',
  //   openTime: '',
  //   single: false,
  //   prizeList: [],
  //   prizes: [],
  // },
  {
    id: '24',
    component: 'ACTIVITY_SIGN',
    category: 'TASK_ELEMENT',
    type: 'ACTIVITY_SIGN',
    label: '签到组件',
    propValue: { groupStyle: {} },
    icon: 'https://media.jiniutech.com/yunying/1_elements/sign.png',
    style: {
      width: 375,
      height: 190,
      textColor: "#545454",
    },
    rewardEnabl: false,
    signStyle: 'BASIC',
    rule: '累计签到即可获得积分',
    freshType: "NONE",
    showMiss: true,
    reachRewards: [],
    signDay: 3,
    signType: 'SEQUENCE',
    // rewardType: 'INTEGRAL',
    dailyRewardType: 'NONE',
    dailyRewardValue: 1,
    unSignBtnImg: `https://media.jiniutech.com/yunying/2_default/sign/UNSIGN_BTN_BASIC.png`,
    signedBtnImg: `https://media.jiniutech.com/yunying/2_default/sign/SIGNED_BTN_BASIC.png`,
    signedIcon: `https://media.jiniutech.com/yunying/2_default/sign/SIGNED_BASIC.png`,
    missIcon: `https://media.jiniutech.com/yunying/2_default/sign/MISS_BASIC.png`,
    unSignIcon: `https://media.jiniutech.com/yunying/2_default/sign/UNSIGN_BASIC.png`,
    lockIcon: `https://media.jiniutech.com/yunying/2_default/sign/LOCK_BASIC.png`,
    prizeList: [],
    prizeIcon: 'https://media.jiniutech.com/yunying/2_default/DT_ZT_DB.png',
  },
  {
    id: '25',
    component: 'GUESS',
    category: 'interaction',
    type: 'GUESS',
    label: '猜涨跌组件',
    icon: 'https://media.jiniutech.com/yunying/1_elements/guess.png',
    style: {
      width: 347.5,
      height: 455,
      previewWidth: 695, // C端设计稿宽度
    },
    riseButtonImage: 'https://media.jiniutech.com/yunying/2_default/guessUpBtn.png',
    fallButtonImage: 'https://media.jiniutech.com/yunying/2_default/guessDownBtn.png',
    indexConfigList: null,
    bettingOptions: null,
    countDownOpen: true,
    customScoreEnable: false
  },
  // {
  //   id: '26',
  //   component: 'RANK',
  //   category: 'base',
  //   type: 'RANK',
  //   label: '排行榜组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/rank.png',
  //   style: {
  //     width: 350,
  //     height: 663,
  //     previewWidth: 700,
  //   },
  //   rankType: 'INTEGRAL',
  //   rankCategoryTypes: ['MONTH_ACC', 'MONTH_ADD'],
  //   showNumber: 10
  // },
  {
    id: '27',
    component: 'INVITE',
    category: 'TASK_ELEMENT',
    type: 'INVITE',
    label: '邀请组件',
    icon: 'https://media.jiniutech.com/yunying/1_elements/invite.png',
    style: {
      width: 330,
      height: 40,
      textColor: "#545454",
      previewWidth: 660,
      boxShadow: '0 0 0 rgba(1,1,1,1)'
    },
    colors: {
      titleColor: 'rgba(84,84,84,1)',
      textColor: 'rgba(134, 140, 148,1)'
    },
    propValue: {
      image: 'https://media.jiniutech.com/yunying/1_elements/invite.png',
      groupStyle: {}
    },
    taskLimitShow: true,
    bindingType: 'AUTO', //  AUTO 自动
    showType: 'DIRECT',
    showStyle: 'TASK',
    inviteButton: 'https://media.jiniutech.com/production/image/279ae4a6-d7e8-44b6-a154-44984e0e17db.png',
    // inviteBackgroundImage:'https://media-test.jiniutech.com/dev/image/c28b8cb0-23d5-49a2-b4fb-bf9cd4465d2e.png',
    confirmBtnColor: 'rgba(6,185,255,1)',
    copyBtnColor: 'rgba(6,185,255,1)',
    copyTip: '复制您的邀请码邀请好友进行绑定',
    fillTip: '填写邀请您注册好友的邀请码，填写之后自动绑定，无法修改',
    goButton: 'https://media.jiniutech.com/yunying/2_default/RW_QWC.png',
    finishButton: 'https://media.jiniutech.com/yunying/2_default/RW_YWC.png',
    image: 'https://media.jiniutech.com/yunying/2_default/RW_ICON.png',
    inviterLimit: false, // 邀请人数限制 不携带至C端
    inviterSetting: {  //  邀请人设置
      enable: false,
      eventType: '',
      eventId: '',
      eventName: '',
      rewardType: 'LEFT_COUNT',
      rewardValue: 0,
      eachCount: 1,
      prizes: [],
      ineligibleTitle: '温馨提示',
      ineligibleTip: '您暂不满足资格哦！',
      ineligibleBtnText: '我知道了',
      clickEvent: {
        clickType: 'NONE  '
      },
      limit: '',
      attendType: 'DAILY',
    },

    inviteeBindSetting: {  // 被邀请人设置
      enable: false,
      eventType: '',
      eventId: '',
      eventName: '',
      ineligibleTitle: '温馨提示',
      ineligibleTip: '您暂不符合受邀资格哦',
      ineligibleBtnText: '我知道了',
      clickEvent: {
        clickType: 'NONE'
      },
    },
    inviteeSetting: {
      enable: false,
      eventType: '',
      eventId: '',
      eventName: '',
      ineligibleTitle: '温馨提示',
      ineligibleTip: '您暂不满足资格哦！',
      ineligibleBtnText: '我知道了',
      clickEvent: {
        clickType: 'NONE'
      },
      rewardType: 'LEFT_COUNT',
      rewardValue: 0,
      prizes: [],
      rewardEnable: false,
      limit: '',
    },
    task: {
      image: 'https://media.jiniutech.com/yunying/2_default/RW_ICON.png',
      name: '这里是任务标题',
      description: '这里是任务描述',
      descShowType: 'QUESTION_MARK',
      taskEventType: '',
      taskEventId: '',
      taskEventName: '',
    }
  },
  {
    id: '28',
    component: 'ANSWER',
    category: 'TASK_ELEMENT',
    type: 'ANSWER',
    label: '答题组件',
    icon: '	https://media.jiniutech.com/yunying/1_elements/answer.png',
    style: {
      width: 200,
      height: 100,
      previewWidth: 400,
      textColor: "rgba(84,84,84,1)",
    },
    propValue: {
      image: 'https://media.jiniutech.com/yunying/1_elements/answer.png',
      groupStyle: {}
    },
    startButton: "https://media.jiniutech.com/yunying/2_default/DT_KS.png",
    banner: "https://media.jiniutech.com/yunying/2_default/DT_BANNER.png",
    drawConsumeType: 'LEFT_COUNT',
    showRemainingValue: true,
    resultBackground: "rgba(255,183,119,1)",
    buttonColor: "rgba(246,88,79,1)",
    hasChangeTip: "快去完成下方任务，获得抽奖机会",
    hasNoChangeTip: "答题次数已达上限，明天再来吧",
    withPrize: true,
    rewardType: 'INTEGRAL',
    integralType: 'ALONE',
    passContext: '太棒了，您已获得奖励',
    unPassContext: '很遗憾，未达成奖励条件',
    passAnswerNumber: 0
  },
  {
    id: '29',
    component: 'FUNDS',
    category: 'prize',
    type: 'FUNDS',
    label: '产品卡片组件',
    propValue: { groupStyle: {} },
    icon: 'https://media.jiniutech.com/yunying/1_elements/funds.png',
    style: {
      width: 350,
      height: 200,
      previewWidth: 700,
      textColor: 'rgba(51,51,51,1)'
    },
    cardStyle: 'SMALL',
    prodType: '1',
    jumpButtonList: [],
    funds: [

      // {
      //   fullName: "华夏成长混合",
      //   comment: "非常好,持续增长",
      //   fundId: "000001",
      //   showType: "growthRate2y",
      //   growthRate1y: -1.8,
      //   growthRate2y: -26.24,
      //   growthRate3y: -12.17,
      //   growthRateDaily: -0.21,
      //   growthRateMonthly: 1.07,
      //   growthRateWeekly: 0.53,
      //   id: Number( Math.random().toString().substr( 3, 12 ) + Date.now() ).toString( 36 )
      // },
      // {
      //   fullName: "中海可转债债券A",
      //   comment: "非常好",
      //   fundId: "000003",
      //   showType: "growthRate2y",
      //   growthRate1y: 2.8,
      //   growthRate2y: -3.1,
      //   growthRate3y: 6.44,
      //   growthRateDaily: -0.59,
      //   growthRateMonthly: 0.36,
      //   growthRateWeekly: -0.59,
      //   id: Number( Math.random().toString().substr( 3, 12 ) + Date.now() ).toString( 36 ),
      // },
    ],
  },
  // {
  //   id: '31',
  //   component: 'EXCHANGE',
  //   category: 'interaction',
  //   type: 'EXCHANGE_NEW',
  //   label: '兑换组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/rank.png',
  //   style: {
  //     width: 350,
  //     height: 340,
  //     previewWidth: 700,
  //     textColor: 'rgba(51,51,51,1)'
  //   },
  //   exchangeButton: 'https://media.jiniutech.com/yunying/2_default/DH_LJDH.png', // 兑换按钮
  //   emptyInventoryExchangeButton: 'https://media.jiniutech.com/yunying/2_default/DH_LJDHC.png', // 无库存兑换按钮
  //   ProductShowType: 'LONG_PIC', // 商品展示样式单列展示
  //   showInventory: false, // 商品库存展示
  //   prizeGroupList: [
  //     {
  //       tagName: '分类一',
  //       prizeList: [],
  //     },
  //     {
  //       tagName: '分类二',
  //       prizeList: [],
  //     },
  //   ],
  //   productShowType: 'LONG_PIC',
  // },
  {
    id: '32',
    component: 'ETFEnroll',
    category: 'prize',
    type: 'ETF_ENROLL',
    label: '报名组件',
    icon: 'https://media.jiniutech.com/yunying/1_elements/etf_enroll.png',
    style: {
      width: 300,
      height: 50,
      previewWidth: 600,
    },
    startTime: '',
    endTime: '',
    gameStartTime: '',
    gameEndTime: '',
    enrollButton: 'https://media.jiniutech.com/yunying/2_default/etf_baoming.png',
    hasEnrollButton: 'https://media.jiniutech.com/production/image/cf822181-c259-4db5-8d7d-4e3d9156e543.png',
    agreement: '',
    desc: '',
    rankDesc: '',
    informedConsentForm: '',
    enableAward: false,
    hasEnrollEvent:{
      clickType: 'NONE',
    },
  },
  // {
  //   id: '33',
  //   component: 'COMPOSITE_GAME',
  //   category: 'interaction',
  //   type: 'COMPOSITE_GAME',
  //   label: '合成游戏组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/composite_game.png',
  //   startButton: 'https://media.jiniutech.com/yunying/daxigua/startGameButton.png',
  //   closeButton: 'https://media.jiniutech.com/yunying/daxigua/stopGameButton.png',
  //   backgroundImage: 'https://media.jiniutech.com/yunying/daxigua/gameBackgroundImg.png',
  //   scoreFrameImg: 'https://media.jiniutech.com/yunying/daxigua/scoreFrameImg.png',
  //   bottomImg: 'https://media.jiniutech.com/yunying/daxigua/backgroundBottomImg.png',
  //   drawConsumeType: 'LEFT_COUNT',
  //   showRemainingValue: true,
  //   scoreRewards: [
  //     {
  //       minScore: '',
  //       maxScore: '',
  //       prizes: [],
  //     }
  //   ],
  //   hasNoChangeTip: '活动次数已达上限，下次再来吧',
  //   hasChangeTip: '快去完成任务，获得抽奖机会吧',
  //   elementsImg: [
  //     'https://media.jiniutech.com/yunying/daxigua/elementImg0.png',
  //     'https://media.jiniutech.com/yunying/daxigua/elementImg1.png',
  //     'https://media.jiniutech.com/yunying/daxigua/elementImg2.png',
  //     'https://media.jiniutech.com/yunying/daxigua/elementImg3.png',
  //     'https://media.jiniutech.com/yunying/daxigua/elementImg4.png',
  //     'https://media.jiniutech.com/yunying/daxigua/elementImg5.png',
  //     'https://media.jiniutech.com/yunying/daxigua/elementImg6.png',
  //     'https://media.jiniutech.com/yunying/daxigua/elementImg7.png',
  //     'https://media.jiniutech.com/yunying/daxigua/elementImg8.png',
  //     'https://media.jiniutech.com/yunying/daxigua/elementImg9.png',
  //     'https://media.jiniutech.com/yunying/daxigua/elementImg10.png',
  //   ],
  //   gameProps: [
  //     {
  //       propType: 'BOMB',
  //       enable: false,
  //       desc: '使用方法：点击使用炸弹道具后触摸屏幕中任意位置，消除指定元素及以下等级的所有小元素。',
  //       cycleInitCount: '',
  //       cycleType: 'DAILY',
  //       associatedTask: {
  //         name: '',
  //         elementId: '',
  //       }
  //     },
  //     {
  //       propType: 'MAGIC_WAND',
  //       enable: false,
  //       desc: '使用方法：点击魔法磅道具，选取屏幕中的任意一个小球，点击后小球即可消除。',
  //       cycleInitCount: '',
  //       cycleType: 'DAILY',
  //       associatedTask: {
  //         name: '',
  //         elementId: '',
  //       }
  //     },
  //     {
  //       propType: 'DOUBLE_CARD',
  //       enable: false,
  //       desc: '使用方法：选择一张翻倍卡进行使用，使用后在结算游戏时，自动将该局的分数乘以指定倍数。',
  //       cycleInitCount: '',
  //       cycleType: 'DAILY',
  //       associatedTask: {
  //         name: '',
  //         elementId: '',
  //       }
  //     },
  //     {
  //       propType: 'TEN_TIMES_CARD',
  //       enable: false,
  //       desc: '使用方法：选择一张翻倍卡进行使用，使用后在结算游戏时，自动将该局的分数乘以指定倍数。',
  //       cycleInitCount: '',
  //       cycleType: 'DAILY',
  //       associatedTask: {
  //         name: '',
  //         elementId: '',
  //       }
  //     },
  //   ],
  //   style: {
  //     width: 222,
  //     height: 140,
  //     previewWidth: 444,
  //     textColor: 'rgba(84,84,84,1)'
  //   },
  // },
  // {
  //   id: '34',
  //   component: 'QRCODE',
  //   category: 'base',
  //   type: 'QRCODE',
  //   label: '二维码组件',
  //   propValue: { groupStyle: {} },
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/qr_code.png',
  //   style: {
  //     width: 150,
  //     height: 150,
  //     previewWidth: 300,
  //   },
  //   logo: 'https://media-test.jiniutech.com/dev/image/a496c6a6-126d-449f-80f6-fc871337be4b.png',
  //   content: 'https://jiniutech.com/us',
  //   frontColor: 'rgba(0,0,0,1)',
  //   backgroundColor: 'rgba(255,255,255,1)',
  // },
  // {
  //   id: '35',
  //   component: 'PAGE',
  //   category: 'base',
  //   type: 'PAGE',
  //   label: '页面容器组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/page_container.png',
  //   style: {
  //     width: 355,
  //     height: 400,
  //     previewWidth: 600,
  //   },
  // },
  // {
  //   id: '36',
  //   component: 'RECEIVE_GOLD',
  //   category: 'interaction',
  //   type: 'RECEIVE_GOLD',
  //   label: '接元宝组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/ICON_YB.jpg',
  //   background: 'https://media.jiniutech.com/yunying/2_default/yb/YB_BG.png',
  //   startButton: 'https://media.jiniutech.com/yunying/2_default/yb/YB_PLAYGAME.png',
  //   characterImage: 'https://media.jiniutech.com/yunying/2_default/yb/YB_CHARACTER.png', // 人物形象
  //   backgroundColor: '#ACDD7A',
  //   gameTimeLimit: 60,
  //   dropSpeed: null,
  //   drawConsumeType: 'LEFT_COUNT',
  //   showRemainingValue: true,
  //   scoreRewards: [
  //     {
  //       minScore: '',
  //       maxScore: '',
  //       prizes: [],
  //     }
  //   ],
  //   propSettings: [
  //     { name: '元宝', type: 'INCREASE', changeScoreColor: '#FF7E20', changeScoreNum: 5, probability: 80, pic: 'https://media.jiniutech.com/yunying/2_default/yb/YUANBAO.png', effectPic: null },
  //     { name: '炸弹', type: 'END', changeScoreColor: null, changeScoreNum: null, probability: 20, pic: 'https://media.jiniutech.com/yunying/2_default/yb/YB_BOMB.png', effectPic: 'https://media.jiniutech.com/yunying/2_default/yb/YB_EXPLODE.png' },
  //   ],
  //   hasNoChangeTip: '活动次数已达上限，下次再来吧',
  //   hasChangeTip: '快去完成任务，获得抽奖机会吧',
  //   style: {
  //     width: 220,
  //     height: 110,
  //     previewWidth: 444,
  //   },
  // },
  // {
  //   id: '37',
  //   component: 'NORMAL_COMMENT',
  //   category: 'interaction',
  //   type: 'NORMAL_COMMENT',
  //   label: '常规评论组件',
  //   propValue: { groupStyle: {} },
  //   commentTitle: '评论标题',
  //   publicCommentTitle: '发表评论>',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/normal_comment.png',
  //   style: {
  //     width: 345,
  //     height: 600,
  //     textAlign: 'center',
  //     previewWidth: 690,
  //   },
  // },
  // {
  //   id: '38',
  //   component: 'OPPOSING_COMMENT',
  //   category: 'interaction',
  //   type: 'OPPOSING_COMMENT',
  //   label: '正反方评论组件',
  //   propValue: { groupStyle: {} },
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/opposing_comment.png',
  //   style: {
  //     width: 345,
  //     height: 600,
  //     textAlign: 'center',
  //     previewWidth: 690,
  //   },
  //   positiveTitle: '正方观点',
  //   negativeTitle: '反方观点',
  //   positiveButton: '发布至正方',
  //   negativeButton: '发布至反方',
  //   enableLike: true,
  //   topicId: '',
  // },
  // {
  //   id: '39',
  //   component: 'FEED_UPGRADE',
  //   category: 'interaction',
  //   type: 'FEED_UPGRADE',
  //   label: '养成游戏组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/cultivate.jpg',
  //   style: {
  //     width: 375,
  //     height: 446,
  //     previewWidth: 750,
  //   },
  //   pendingImg: "https://media-test.jiniutech.com/dev/image/52fcbb13-e2e0-47bc-98fd-ed0699788583.png", // 领养形象
  //   adoptBtnImg: "https://media-test.jiniutech.com/dev/image/e73349fb-b80e-4d88-b4e8-6b1ad79d0f2a.png", // 创建角色按钮图
  //   levels: [
  //     {
  //       name: '无名小卒',
  //       image: "https://media-test.jiniutech.com/dev/image/52fcbb13-e2e0-47bc-98fd-ed0699788583.png",
  //       expValue: 0,
  //     },
  //     {
  //       name: '身有分文',
  //       image: "https://media-test.jiniutech.com/dev/image/53770ac8-2105-4e8a-a770-c8cd311d453d.png",
  //       expValue: 3000,
  //     },
  //     {
  //       name: '小有资产',
  //       image: "https://media-test.jiniutech.com/dev/image/efc05fdb-d8a1-4060-b3f7-1226a578d3d0.png",
  //       expValue: 6000,
  //     },
  //     {
  //       name: '富的流油',
  //       image: "https://media-test.jiniutech.com/dev/image/de1636c2-fd0c-4869-90d3-a2144aa3c47f.png",
  //       expValue: 10000,
  //     },
  //     {
  //       name: '盆满钵满',
  //       image: "https://media-test.jiniutech.com/dev/image/bf3418e9-a95b-4ac8-9f63-7450623450aa.png",
  //       expValue: 12000,
  //     },
  //     {
  //       name: '家财万贯',
  //       image: "https://media-test.jiniutech.com/dev/image/7bfaa3ca-d092-4055-ba73-d11e35909e41.png",
  //       expValue: 14000,
  //     },
  //     {
  //       name: '富可敌国',
  //       image: "https://media-test.jiniutech.com/dev/image/0283c9de-b169-4d79-9753-5339d4f4c5bc.png",
  //       expValue: 20000,
  //     },
  //   ],
  //   upgradeType: 'MANUAL_CONSUME',
  //   initImg: 'https://media-test.jiniutech.com/dev/image/52fcbb13-e2e0-47bc-98fd-ed0699788583.png',
  //   upgradeImg: "https://media-test.jiniutech.com/dev/image/f7725105-5673-42a4-ad76-615fb95a470a.gif",
  //   upgradeBtnImg: "https://media-test.jiniutech.com/dev/image/992315c0-c0ca-4fc4-b873-795e3062c3e0.png",
  //   titleImg: "https://media-test.jiniutech.com/dev/image/6aa65908-5f7f-490d-b647-5f7478e164f9.png",
  //   scoreImg: "https://media-test.jiniutech.com/dev/image/c67eb8ad-edea-4b53-8c32-5890b00b73de.png",
  //   levelUpDataAreaImg: "https://media-test.jiniutech.com/dev/image/7ab519ea-d2f4-4cd4-a8b3-80058018cca6.png"
  // },
  // {
  //   id: '40',
  //   component: 'BARRAGE',
  //   category: 'interaction',
  //   type: 'BARRAGE',
  //   label: '弹幕组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/BARRAGE.jpg',
  //   style: {
  //     width: 300,
  //     height: 3 * 37,
  //     previewWidth: 600,
  //     fontSize: 14
  //   },
  //   records: ['太厉害了', '请再接再厉吧~', '恭喜您获得奖励！', '为你点赞！', '参赛赢大奖 万元好礼等你拿', '用实际行动拓宽财富增值的道路！'],
  //   bulletFont: '#000',
  //   bulletCount: 50,
  //   bulletRowCount: 3,
  //   limit: 20,
  //   bulletBackground: '',
  //   borderColor: '',
  //   bulletLineSpace: 1,
  //   transparency: 1,
  //   // bulletSimulationCount:10,
  //   dataType: 'REWARD'
  // },
  // {
  //   id: '41',
  //   component: 'ETF_HOT_RANK',
  //   category: 'prize',
  //   type: 'ETF_HOT_RANK',
  //   label: 'ETF榜单组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/ETF_LIST.jpg',
  //   style: {
  //     width: 375,
  //     height: 600,
  //   },
  //   directShowNum: 10,
  //   moreButton: 'url',
  //   rankStyle: 'STYLE_ONE',
  //   ranks:
  //     [
  //       {
  //         title: "收益榜",
  //         manual: false,
  //         merchantId: "changcheng",
  //         datasourceId: "1",
  //         fields: [
  //           "nameCode",
  //           "latestPrice",
  //           "netValue",
  //           "growthRateDaily",
  //         ],
  //       },
  //       {
  //         title: "精选榜",
  //         manual: true,
  //         funds: [
  //           {
  //             id: 1,
  //             fullName: "华夏成长混合",
  //             fundId: "000001",
  //           },
  //           {
  //             id: 2,
  //             fullName: "中海可转债债券A",
  //             fundId: "000003",
  //           },
  //         ],
  //         fields: [
  //           "nameCode",
  //           "latestPrice",
  //           "netValue",
  //           "growthRateDaily",
  //         ],
  //       },
  //     ],
  //   propValue: {
  //     styleObj: {
  //       topImg: { left: 0, width: '100%' },
  //       bgColor: { backgroundColor: '#fdd882' },
  //       mainContent: { backgroundColor: '#fffbea' },
  //       tabHeader: {
  //         background: '#fff3e5', color: '#bf7243', fontSize: 'calc(26 / 32 * 1rem)', borderRadius: 'calc(4 / 32 * 1rem)',
  //       },
  //       tabContent: { backgroundColor: '#fff' },
  //       tabNav: { background: 'linear-gradient(180deg, #ff9d03 0%, #ffc974 100%)' },
  //       active: { background: 'linear-gradient(270deg, #eb3b3b 0%, #fe543f 59%, #ff6860 100%)' },
  //       tabItem: {},
  //       name: { fontSize: 'calc(26 / 32 * 1rem)' },
  //       code: { color: '#5c5c5c' },
  //     },
  //     groupStyle: {}
  //   },
  // },
  // {
  //   id: 99,
  //   component: 'K_LINE_GAME',
  //   category: 'interaction',
  //   type: 'K_LINE_GAME',
  //   label: 'K线游戏组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/K-line.png',
  //   style: {
  //     width: 200,
  //     height: 90,
  //   },
  //   drawConsumeType: "LEFT_COUNT",
  //   showRemainingValue: true,
  //   startButton: 'https://media.jiniutech.com/yunying/2_default/yb/YB_PLAYGAME.png',
  //   hasNoChangeTip: '今日游戏次数已达上限，下次再来吧',
  //   hasChangeTip: '快去完成任务，获得游戏机会吧',
  //   enableWinAward: true,
  //   enableDrawAward: false,
  // },
  // {
  //   id: '43',
  //   component: 'ETF_RANK',
  //   category: 'prize',
  //   type: 'ETF_RANK',
  //   label: 'ETF排行榜组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/ETF_RANKING_LIAST.jpg',
  //   style: {
  //     width: 375,
  //     height: 610,
  //     previewWidth: 750,
  //   },
  //   rankStyle: 'STYLE_ONE',
  //   datasourceId: 'changcheng',
  //   showNum: 10,
  //   rankTypeList: ['DAY', 'WEEK', 'MONTH', 'OVERALL'],
  //   fields: ['rank', 'fundAccount', 'returnRate']
  // },
  {
    id: '44',
    component: 'LIKE',
    category: 'base',
    type: 'LIKE',
    label: '点赞组件',
    icon: 'https://media.jiniutech.com/yunying/1_elements/like.jpg',
    style: {
      width: 100,
      height: 100,
      previewWidth: 200,
    },
    likeStyle: 'DEFAULT',
    canCancel: true,
    showLikeCount: true,
    initLikeCount: 0,
    likeColor: '#1F3883',
    unLikeColor: '#000',
    likeIcon: 'like'
  },
  {
    id: '45',
    component: 'QUESTIONNAIRE',
    category: 'interaction',
    type: 'QUESTIONNAIRE',
    label: '问卷组件',
    icon: 'https://media.jiniutech.com/yunying/1_elements/response.jpg',
    style: {
      width: 375,
      height: 472,
      backgroundColor: '#fff'
    },
    submitButtonStyle: 'DEFAULT',
    titleColor: '#111E36',
    descriptionColor: '#5B606F',
    optionColor: '#111E36',
    spacing: 20,
    popupTitle: '提交成功',
    popupButtonText: '我知道了',
    submitButtonBackgroundColor: '#275fd5',
    submitButtonTextColor: '#fff',
    submitButtonText: '提交问卷',
    question: [

      {
        isOpen: true,
        answer: true,
        virtualId: Number( Math.random().toString().substr( 3, 12 ) + Date.now() ).toString( 36 ),
        title: `您的姓名`,
        topic: 'SINGLE_TEXT',
        description: '请填写您的姓名',
        extended: {}
      },
      {
        isOpen: true,
        answer: true,
        virtualId: Number( Math.random().toString().substr( 3, 12 ) + Date.now() ).toString( 36 ),
        title: `您的性别`,
        topic: 'SINGLE_CHOICE',
        optionsList: ["男", "女"],
        description: '请选择您的性别'
      },
      {
        isOpen: true,
        answer: true,
        virtualId: Number( Math.random().toString().substr( 3, 12 ) + Date.now() ).toString( 36 ),
        title: `您的手机号`,
        topic: 'SINGLE_TEXT',
        description: '请填写您的手机号',
        extended: {}
      },
    ]
  },
  // {
  //   id: '46',
  //   component: 'PUZZLE_GAME',
  //   category: 'interaction',
  //   type: 'PUZZLE_GAME',
  //   label: '拼图组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/Puzzle.jpg',
  //   style: {
  //     width: 220,
  //     height: 110,
  //     previewWidth: 444,
  //   },
  //   previewTime: 3,
  //   puzzleTime: 60,
  //   drawConsumeType: 'LEFT_COUNT',
  //   showRemainingValue: true,
  //   backgroundImage: "https://media.jiniutech.com/production/image/e9d897c9-3b17-4528-94f1-f97fb099ba0a.jpeg",
  //   backgroundColor: '#F9CA75',
  //   startButton: "https://media-test.jiniutech.com/dev/image/d4795624-5e7f-4d7d-8caa-c201229a0065.png",
  //   hasChangeTip: '快去完成任务，获得游戏机会吧',
  //   hasNoChangeTip: '今日游戏次数已达上限，下次再来吧',
  //   puzzleGames: [
  //     {
  //       image: 'https://media.jiniutech.com/production/image/36a569e3-9972-46d9-9812-b1714ba73743.png',
  //       name: '拼图1',
  //       virtualId: Number( Math.random().toString().substr( 3, 12 ) + Date.now() ).toString( 36 ),
  //       width: 3,
  //       height: 4
  //     },
  //   ]
  // },
  // {
  //   id: '47',
  //   component: 'DOLL_MACHINE',
  //   category: 'interaction',
  //   type: 'DOLL_MACHINE',
  //   label: '娃娃机组件',
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/Dol-machine.jpg',
  //   style: {
  //     width: 220,
  //     height: 130,
  //     previewWidth: 440,
  //   },
  //   startButton: 'https://media-test.jiniutech.com/dev/image/a23b5972-5ecc-4040-b202-9455db164b75.png',
  //   drawConsumeType: 'LEFT_COUNT',
  //   showRemainingValue: true,
  //   drawConsumeValue: '',
  //   hasNoChangeTip: '活动次数已达上限，下次再来吧',
  //   hasChangeTip: '快去完成任务，获得抽奖机会吧',
  //   gameTime: 60,
  //   dropSpeed: 2,
  //   backgroundImage: 'https://media-test.jiniutech.com/dev/image/cbecc7a1-67a4-440f-a8ea-8597f0dfe809.png',
  //   backgroundColor: '',
  //   dollSettings: [
  //     {
  //       name: '娃娃一',
  //       score: '1',
  //       dollImg: 'https://media-test.jiniutech.com/dev/image/a54db149-d92f-4fe6-8893-d8145c3679db.png'
  //     },
  //     {
  //       name: '娃娃二',
  //       score: '2',
  //       dollImg: 'https://media-test.jiniutech.com/dev/image/9ed41ef0-bf8a-44d7-9ec6-53b06970e444.png'
  //     },
  //     {
  //       name: '娃娃三',
  //       score: '5',
  //       dollImg: 'https://media-test.jiniutech.com/dev/image/850f5368-4401-486f-894d-41bb1eafe1f5.png'
  //     },
  //     {
  //       name: '娃娃四',
  //       score: '10',
  //       dollImg: 'https://media-test.jiniutech.com/dev/image/6f8960db-fb8a-4bef-80b3-033e1e6c8588.png'
  //     },
  //     {
  //       name: '娃娃五',
  //       score: '15',
  //       dollImg: 'https://media-test.jiniutech.com/dev/image/8535064d-85fd-4c25-8332-f42f1a087a47.png'
  //     },
  //   ],
  //   scoreRewards: [
  //     {
  //       minScore: '',
  //       maxScore: '',
  //       prizes: [],
  //     }
  //   ],

  // },
  // {
  //   id: '48',
  //   component: 'POP_UP',
  //   category: 'base',
  //   type: 'POP_UP',
  //   label: '弹窗组件',
  //   icon: "https://media.jiniutech.com/yunying/1_elements/pop.png",
  //   style: {
  //     width: 300,
  //     height: 300,
  //   },
  //   condition:'TIMES',
  //   isAll:true,
  //   popType:'RICH',
  //   isShowClose:true,
  //   confirmStyle:'DEFAULT',
  //   background:'',
  //   confirmText:'我知道了',
  //   confirmColor:'',
  // },
  {
    id: '49',
    component: 'FLIP',
    category: 'REWARD_ELEMENT',
    type: 'FLIP',
    label: '翻牌组件',
    propValue: {
      image: 'https://media.jiniutech.com/yunying/2_default/flip/Flip.png',
      groupStyle: {},
    },
    icon: 'https://media.jiniutech.com/yunying/2_default/flip/Flip.png',
    style: {
      width: 345,
      height: 540,
      textColor: 'rgba(84,84,84,1)',
      previewWidth: 690,
    },
    startTime: '',
    endTime: '',
    drawConsumeType: 'LEFT_COUNT',
    showRemainingValue: true,
    number:'9',
    hasNoChangeTip: '活动次数已达上限，下次再来吧',
    hasChangeTip: '快去完成任务，获得抽奖机会吧',
    // startFlipButton:'https://media.jiniutech.com/yunying/2_default/flip/Flip_KSFP.png',
    startFlipButton:'https://media.jiniutech.com/production/image/30108af1-181f-43fc-ab22-13b2e834cb76.png',
    // pleaseFlipButton:'https://media.jiniutech.com/yunying/2_default/flip/Flip_QFP.png',
    pleaseFlipButton:'https://media.jiniutech.com/production/image/2b6f2bd0-435f-490e-b5d5-afbfd6ace2ec.png',
    cardBehind:'https://media.jiniutech.com/yunying/2_default/flip/Flip_BM.png',
    cardFront:'https://media.jiniutech.com/yunying/2_default/flip/Flip_ZM.png',
    drawImage: 'https://media.jiniutech.com/yunying/2_default/JGG_CJT.gif',
    prizes: [
      {
        image: 'https://media.jiniutech.com/yunying/2_default/XXCY.png',
        itemName: '谢谢参与',
        itemPosition: '1,3,7,9',
        prizeVirtualId: 'eiu94fccngg00000',
        probability: 50,
      },
      {
        image: 'https://media.jiniutech.com/yunying/2_default/HBY_HBT.png',
        itemName: '现金红包',
        itemPosition: '2,4,5,6,8',
        probability: 50,
        prizeVirtualId: 'uqjvmvlg4z400000',
      },
    ],
  },
  {
    id: '50',
    component: 'VOTING',
    category: 'prize',
    type: 'VOTING',
    label: '投票组件',
    icon: 'https://media.jiniutech.com/production/image/9de12fcf-6edc-4ab2-99da-fd04f6520888.png',
    style: {
      width: 345,
      height: 450,
      previewWidth: 690,
      backgroundColor: '#fff'
    },
    startTime: '',
    endTime: '',
    showAttendUser: true,
    submitButtonImage:'https://media.jiniutech.com/production/image/f33fe963-ff8f-4e53-ad92-9d47ed40e836.png',
    noSubmitButtonImage:'https://media.jiniutech.com/production/image/fa7190c0-cd1c-4dc7-b0ce-b4ae351db817.png',
    task:{
      clickEvent: {
        clickType: 'NONE',
      },
      ineligibleTitle: '温馨提示',
      ineligibleTip: '您暂不符合受邀资格哦',
      ineligibleBtnText: '我知道了',
    },
    questionType:'SINGLE_CHOICE',
    title:'为了提升客户满意度和市场份额，您认为公司最应该优先投资哪个领域？',
    description:'为了更好地适应市场变化，增强客户体验，我们需要确定下一步的重点投资方向。请从以下选项中选择您认为最紧迫的一个。',
    optionsList:[
      {
        context:'数字化平台升级',
      },
      {
        context:'新产品开发',
      },
      {
        context:'客户服务质量提升',
      },
      {
        context:'风险管理加强',
      },
      // {
      //   id:'5',
      //   context:'国际市场拓展',
      // },
    ],
    votingLimit:'',
    isShowVoteData:true,
    showVoteDataType:'PERCENT',
    uncheckFont:'#222222',
    checkFont:'#C98006',
    uncheckBackground:'#F5F6FD',
    checkBackground:'#F5F6FD',
    uncheckScaleBackground:'#EEEEEE',
    checkScaleBackground:'#FFF2DE',
  },
  {
    id: '51',
    component: 'BIND_GROUP',
    category: 'interaction',
    type: 'BIND_GROUP',
    label: '拼团组件',
    icon: 'https://media.jiniutech.com/yunying/1_elements/like.jpg',
    style: {
      width: 345,
      height: 265,
      previewWidth: 690,
      backgroundColor: '#fff',
      textColor: 'rgba(153, 153, 153, 1)',
    },
    memberAmount:2,
    attendLimit:1,
    inviteButtonImg:'https://media.jiniutech.com/production/image/760c5036-ca32-4b44-811d-0c3d748eca88.png',
    drawButtonImg:'https://media.jiniutech.com/production/image/07dafcb6-6dae-47a2-9e7c-1c5d52754040.png',
    startGroupButtonImg:'https://media.jiniutech.com/production/image/9f4d10eb-63a8-4f3e-a53f-cc54b1768b13.png',
    awardButtonImg:'https://media.jiniutech.com/production/image/7dd0c4d7-57af-4660-baf2-22bb7e237d2b.png'
  },
  {
    id: '52',
    component: 'FLASH_SALE',
    category: 'interaction',
    type: 'FLASH_SALE',
    label: '秒杀组件',
    propValue: { groupStyle: {} },
    icon: 'https://media.jiniutech.com/production/image/50e43dd2-33d5-4de6-a0da-df0767f496ec.png',
    style: {
      width: 345,
      height: 139,
      previewWidth: 690,
    },
    backgroundImage: 'https://media.jiniutech.com/production/image/f1084a93-0589-4e8d-9746-9a45599931af.png',
    beforeButton: 'https://media.jiniutech.com/production/image/965b2dae-5949-4ef6-b5ed-89efec58115a.png',
    inStockButton: 'https://media.jiniutech.com/production/image/485a8260-ac5e-475a-ad9d-a7bcaea39da7.png',
    outStockButton: 'https://media.jiniutech.com/production/image/6e317515-578d-4ce1-95ce-8edecaa9d239.png',
    endButton: 'https://media.jiniutech.com/production/image/a9aa7164-9a10-45cf-ae6e-fd07b6395f56.png',
    colors: {
      nameColor: 'rgba(0, 0, 0, 1)',
      originalPriceColor: 'rgba(154, 154, 154, 1)',
      presentPriceColor: 'rgba(250, 44, 25, 1)',
      countDownColor: 'rgba(255, 255, 255, 1)',
      describeColor: 'rgba(154, 154, 154,1)',
    }
  },
  // 空白组件与自定义组件保持在最后两个,请在上方添加组件
  // {
  //   id: '999',
  //   component: 'EMPTY',
  //   category: 'base',
  //   type: 'EMPTY',
  //   label: '空白组件',
  //   icon: "https://media-test.jiniutech.com/dev/image/e6eba026-1112-4743-89eb-43d3b3f5e8d0.png",
  //   style: {
  //     width: 300,
  //     height: 300,
  //   },
  // },
  // {
  //   id: '100',
  //   component: 'CUSTOM',
  //   category: 'base',
  //   type: 'CUSTOM',
  //   label: '自定义组件',
  //   propValue: { groupStyle: {} },
  //   icon: 'https://media.jiniutech.com/yunying/1_elements/custom.jpg',
  //   style: {
  //     width: 300,
  //     height: 20,
  //     textAlign: 'center',
  //   },
  // },
];
/* eslint-disable */
for (let i = 0, len = list.length; i < len; i++) {
  const item = list[i];
  item.style = { ...commonStyle, ...item.style };
  list[i] = { ...commonAttr, ...item };
}

export default list;
